### ISSUE TITLE
Could not find com.github.xuexiangjys:XUpdate:1.1.4.

### ISSUE THREAD

**Issue by qinkangwu** [xuexiangjys/react-native-xupdate#6]
`Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.xuexiangjys:XUpdate:1.1.4.
     Searched in the following locations:
       - file:/Users/qinkangwu/Library/Android/sdk/extras/m2repository/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.pom
       - file:/Users/qinkangwu/Library/Android/sdk/extras/m2repository/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.jar
       - file:/Users/qinkangwu/Library/Android/sdk/extras/google/m2repository/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.pom
       - file:/Users/qinkangwu/Library/Android/sdk/extras/google/m2repository/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.jar
       - file:/Users/qinkangwu/Library/Android/sdk/extras/android/m2repository/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.pom
       - file:/Users/qinkangwu/Library/Android/sdk/extras/android/m2repository/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.jar
       - file:/Users/qinkangwu/.m2/repository/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.pom
       - file:/Users/qinkangwu/.m2/repository/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.jar
       - https://dl.google.com/dl/android/maven2/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.pom
       - https://dl.google.com/dl/android/maven2/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.jar
       - https://jcenter.bintray.com/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.pom
       - https://jcenter.bintray.com/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.jar
       - file:/Users/qinkangwu/lxkjPro/water_app/node_modules/react-native/android/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.pom
       - file:/Users/qinkangwu/lxkjPro/water_app/node_modules/react-native/android/com/github/xuexiangjys/XUpdate/1.1.4/XUpdate-1.1.4.jar
     Required by:
         project :app > project :react-native-xupdate-new`

大佬麻烦看一下

**Comment by xuexiangjys** [comment]
maven { url 'https://jitpack.io' }
